name: aloula2

on:
  schedule:
    - cron: '*/5 * * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: config
        run: |
          git config --global user.email "<>"
          git config --global user.name "aloula2 bot"

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          
      - name: Install requests module
        run: python3 -m pip install requests

      - name: Execute Python script
        run: python3 ressources/mar/aloula2.py > ressources/mar/aloula2.m3u8

      - name: git add
        run: |
          git add -A
          ls -la 
          
      - name: commit & push
        run: |
          git add -A
          if git diff --cached --quiet; then
            echo "No changes to commit"
          else
            git commit -m "aloula2 updated"
            git push origin master
          fi
