name: shmax

on:
  schedule:
    - cron: '16 */04 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    continue-on-error: true  # ✅ This prevents red failure status / notifications

    steps:
      - uses: actions/checkout@v3

      - name: config
        run: |
          git config --global user.email "<>"
          git config --global user.name "shmax bot"

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip

      - name: Install requests module
        run: python3 -m pip install requests

      - name: Execute Python script max
        run: python3 ressources/tur/shmax.py > ressources/tur/shmax.m3u8

      - name: git add
        run: |
          git add -A
          ls -la 

      - name: commit & push
        run: |
          git pull origin master
          git commit -m "shmax updated" || echo "No changes to commit"
          git push origin master
