name: tf1z

on:
  workflow_dispatch:
  schedule:
    - cron: '1 */2 * * *'

jobs:
  update-tf1-stream:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout your repository
        uses: actions/checkout@v3

      - name: Fetch content
        run: |
          curl -sL https://raw.githubusercontent.com/paradise-91/paratv/main/playlists/paratv/main/filter/raw.m3u -o source_raw.m3u

      - name: Extract content line
        id: extract_line
        run: |
          line=$(awk '/#EXTINF:-1,TF1 \[720p-tf1.fr\]/ {getline; print}' source_raw.m3u)
          echo "TF1_LINE=$line" >> $GITHUB_ENV

      - name: Replace the line in m3u
        run: |
          awk -v new="$TF1_LINE" '
          {
          print $0
          if ($0 ~ /^TF1_$/) {
          getline   # Skip the current next line
          print new # Insert new line
          next
          }
          }
          ' all.m3u > temp && mv temp all.m3u

      - name: Commit and push changes
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add all.m3u
          git commit -m "tfz update" || echo "No changes to commit"
          git push origin master
