name: Generate TF1 M3U8

on:
  schedule:
    - cron: '11 */3 * * *'
  
  workflow_dispatch:

jobs:
  generate-playlist:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install requests

      - name: Generate playlist and write to file
        run: |
          python3 <<EOF
          import re
          import requests
          import os

          url = "https://raw.githubusercontent.com/schumijo/iptv/refs/heads/main/playlists/mytf1/tf1.m3u8"
          response = requests.get(url)
          content = response.text

          match = re.search(r'9023effe3c16b0475d35e9f31c778b5c/([^/]+)/out/', content)
          if not match:
              raise ValueError("Token not found")

          token = match.group(1)

          template_m3u8 = f"""#EXTM3U
          #EXT-X-VERSION:6
          #EXT-X-INDEPENDENT-SEGMENTS
          #EXT-X-STREAM-INF:BANDWIDTH=2207158,AVERAGE-BANDWIDTH=2010952,RESOLUTION=1024x576,FRAME-RATE=25,CODECS="avc1.4D401F,mp4a.40.2",SUBTITLES="subtitles",AUDIO="audio_0"
          https://live-tf1-hls-ssai.cdn-0.diff.tf1.fr/9023effe3c16b0475d35e9f31c778b5c/{token}/out/v1/2a5ef2a4ce4a41209e0a881074d15932/tf1-cmaf/index_2.m3u8
          #EXT-X-MEDIA:TYPE=AUDIO,GROUP-ID="audio_0",CHANNELS="2",NAME="fra",LANGUAGE="fra",DEFAULT=YES,AUTOSELECT=YES,URI="https://live-tf1-hls-ssai.cdn-0.diff.tf1.fr/9023effe3c16b0475d35e9f31c778b5c/{token}/out/v1/2a5ef2a4ce4a41209e0a881074d15932/tf1-cmaf/index_12_0.m3u8"
          """

          os.makedirs("ressources/btv/py", exist_ok=True)
          with open("ressources/btv/py/tfun.m3u8", "w") as f:
              f.write(template_m3u8)
          EOF

      - name: Show generated file
        run: cat ressources/btv/py/tfun.m3u8
